Updated test

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -811,7 +811,81 @@ jobs:
           else
             cat "deleted_files/test/test deleted.txt"
           fi
-  
+
+  test-dir-names-deleted-files-include-only-deleted-dirs-single-file:
+    name: Test dir names deleted files include only deleted dirs single file
+    runs-on: ubuntu-latest
+    needs: build
+    if: needs.build.outputs.files_changed != 'true'
+    steps:
+      - name: Checkout branch
+        uses: actions/checkout@v4
+        with:
+          ref: 920856cf
+          repository: ${{ github.event.pull_request.head.repo.full_name }}
+          submodules: true
+          fetch-depth: 3
+      - name: Run changed-files with dir_names and dir_names_deleted_files_include_only_deleted_dirs with a single file deleted withing the test directory
+        id: changed-files-dir-names-deleted-files-include-only-deleted-dirs-single-file
+        uses: ./
+        with:
+          base_sha: 920856cf
+          sha: a52f8621
+          dir_names: true
+          dir_names_deleted_files_include_only_deleted_dirs: true
+      - name: Show output
+        run: |
+          echo '${{ toJSON(steps.changed-files-dir-names-deleted-files-include-only-deleted-dirs-single-file.outputs) }}'
+        shell:
+          bash
+      - name: Check deleted_files output
+        if: steps.changed-files-dir-names-deleted-files-include-only-deleted-dirs-single-file.outputs.deleted_files != ''
+        run: |
+          echo "Invalid output: Expected '' got (${{ steps.changed-files-dir-names-deleted-files-include-only-deleted-dirs-single-file.outputs.deleted_files }})"
+          exit 1
+        shell:
+          bash
+  test-dir-names-deleted-files-include-only-deleted-dirs-directory:
+    name: Test dir names deleted files include only deleted dirs
+    runs-on: ubuntu-latest
+    needs: build
+    if: needs.build.outputs.files_changed != 'true'
+    steps:
+      - name: Checkout branch
+        uses: actions/checkout@v4
+        with:
+          ref: 920856cf
+          repository: ${{ github.event.pull_request.head.repo.full_name }}
+          submodules: true
+          fetch-depth: 3
+      - name: Run changed-files with dir_names and dir_names_deleted_files_include_only_deleted_dirs with the test directory deleted
+        id: changed-files-dir-names-deleted-files-include-only-deleted-dirs-directory
+        uses: ./
+        with:
+          base_sha: 920856cf
+          sha: cd1e384
+          dir_names: true
+          dir_names_deleted_files_include_only_deleted_dirs: true
+      - name: Show output
+        run: |
+          echo '${{ toJSON(steps.changed-files-dir-names-deleted-files-include-only-deleted-dirs-directory.outputs) }}'
+        shell:
+          bash
+      - name: Check deleted_files output on non windows platform
+        if: steps.changed-files-dir-names-deleted-files-include-only-deleted-dirs-directory.outputs.deleted_files != 'test/test3' && runner.os != 'Windows'
+        run: |
+          echo "Invalid output: Expected (test/test3) got (${{ steps.changed-files-dir-names-deleted-files-include-only-deleted-dirs-directory.outputs.deleted_files }})"
+          exit 1
+        shell:
+          bash
+      - name: Check deleted_files output on windows platform
+        if: "!contains(steps.changed-files-dir-names-deleted-files-include-only-deleted-dirs-directory.outputs.deleted_files, 'test\\test3') && runner.os == 'Windows'"
+        run: |
+          echo "Invalid output: Expected (test\\test3) got (${{ steps.changed-files-dir-names-deleted-files-include-only-deleted-dirs-directory.outputs.deleted_files }})"
+          exit 1
+        shell:
+          bash
+
   test-since-last-remote-commit:
     name: Test changed-files since last remote commit
     runs-on: ubuntu-latest
@@ -1052,34 +1126,6 @@ jobs:
         if: steps.changed-files-dir-names-specific.outputs.all_changed_files != 'test'
         run: |
           echo "Invalid output: Expected (test) got (${{ steps.changed-files-dir-names-specific.outputs.all_changed_files }})"
-          exit 1
-        shell:
-          bash
-      - name: Run changed-files with dir_names and dir_names_deleted_files_include_only_deleted_dirs with the test directory deleted
-        id: changed-files-dir-names-deleted-files-include-only-deleted-dirs-directory
-        uses: ./
-        with:
-          base_sha: 920856cf
-          sha: cd1e384
-          fetch_depth: 60000
-          dir_names: true
-          dir_names_deleted_files_include_only_deleted_dirs: true
-      - name: Show output
-        run: |
-          echo '${{ toJSON(steps.changed-files-dir-names-deleted-files-include-only-deleted-dirs-directory.outputs) }}'
-        shell:
-          bash
-      - name: Check deleted_files output on non windows platform
-        if: steps.changed-files-dir-names-deleted-files-include-only-deleted-dirs-directory.outputs.deleted_files != 'test/test3' && runner.os != 'Windows'
-        run: |
-          echo "Invalid output: Expected (test/test3) got (${{ steps.changed-files-dir-names-deleted-files-include-only-deleted-dirs-directory.outputs.deleted_files }})"
-          exit 1
-        shell:
-          bash
-      - name: Check deleted_files output on windows platform
-        if: "!contains(steps.changed-files-dir-names-deleted-files-include-only-deleted-dirs-directory.outputs.deleted_files, 'test\\test3') && runner.os == 'Windows'"
-        run: |
-          echo "Invalid output: Expected (test\\test3) got (${{ steps.changed-files-dir-names-deleted-files-include-only-deleted-dirs-directory.outputs.deleted_files }})"
           exit 1
         shell:
           bash
