Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -20,6 +20,67 @@ jobs:
       - run: |
           echo "$GITHUB_EVENT_PATH"
           cat "$GITHUB_EVENT_PATH"
+          if [ -z "$PR_NUMBER" ]; then
+            PR_NUMBER=$(jq -r ".pull_request.number" "$GITHUB_EVENT_PATH")
+            if [[ "$PR_NUMBER" == "null" ]]; then
+              PR_NUMBER=$(jq -r ".issue.number" "$GITHUB_EVENT_PATH")
+            fi
+            if [[ "$PR_NUMBER" == "null" ]]; then
+              echo "Failed to determine PR Number."
+              exit 1
+            fi
+          fi
+          echo "$PR_NUMBER"
+          URI=https://api.github.com
+          API_HEADER="Accept: application/vnd.github.v3+json"
+          AUTH_HEADER="Authorization: token $GITHUB_TOKEN"
+
+          MAX_RETRIES=${MAX_RETRIES:-6}
+          RETRY_INTERVAL=${RETRY_INTERVAL:-10}
+          REBASEABLE=""
+          pr_resp=""
+          for ((i = 0 ; i < $MAX_RETRIES ; i++)); do
+            pr_resp=$(curl -X GET -s -H "${AUTH_HEADER}" -H "${API_HEADER}" \
+              "${URI}/repos/$GITHUB_REPOSITORY/pulls/$PR_NUMBER")
+            REBASEABLE=$(echo "$pr_resp" | jq -r .rebaseable)
+            if [[ "$REBASEABLE" == "null" ]]; then
+              echo "The PR is not ready to rebase, retry after $RETRY_INTERVAL seconds"
+              sleep $RETRY_INTERVAL
+              continue
+            else
+              break
+            fi
+          done
+
+          if [[ "$REBASEABLE" != "true" ]] ; then
+            echo "GitHub doesn't think that the PR is rebaseable!"
+            exit 1
+          fi
+
+          BASE_REPO=$(echo "$pr_resp" | jq -r .base.repo.full_name)
+          BASE_BRANCH=$(echo "$pr_resp" | jq -r .base.ref)
+
+          USER_LOGIN=$(jq -r ".comment.user.login" "$GITHUB_EVENT_PATH")
+
+          user_resp=$(curl -X GET -s -H "${AUTH_HEADER}" -H "${API_HEADER}" \
+            "${URI}/users/${USER_LOGIN}")
+
+          USER_NAME=$(echo "$user_resp" | jq -r ".name")
+          if [[ "$USER_NAME" == "null" ]]; then
+            USER_NAME=$USER_LOGIN
+          fi
+          USER_NAME="${USER_NAME} (Rebase PR Action)"
+
+          USER_EMAIL=$(echo "$user_resp" | jq -r ".email")
+          if [[ "$USER_EMAIL" == "null" ]]; then
+            USER_EMAIL="$USER_LOGIN@users.noreply.github.com"
+          fi
+          
+          echo "$BASE_REPO"
+          echo "$BASE_BRANCH"
+          echo "$USER_LOGIN"
+          echo "$USER_NAME"
+          echo "$USER_EMAIL"
       - name: Run changed-files with defaults
         id: changed-files
         uses: ./
