chore: clean up test

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -99,16 +99,20 @@ jobs:
         uses: actions/checkout@v3
         with:
           fetch-depth: 0
-      
-      - run: |
-          git log -1 --format="%H" --date=local --until="2022-08-20" | grep -n 8d5c4478e28f7b7189cd93c195aa9d4f0992da90
     
       - name: Run changed-files since 2022-08-19
         id: changed-files-since
         uses: ./
-        continue-on-error: true
         with:
           since: "2022-08-19"
+
+      - name: Check output
+        if: "!contains(steps.changed-files-since.outputs.all_changed_files, '.github/workflows/sync-release-version.yml')"
+        run: |
+          echo "Invalid output: Expected to include (.github/workflows/sync-release-version.yml) got (${{ steps.changed-files-since.outputs.all_changed_files }})"
+          exit 1
+        shell:
+          bash
       
       - name: Show output
         run: |
@@ -119,9 +123,16 @@ jobs:
       - name: Run changed-files until 2022-08-20
         id: changed-files-until
         uses: ./
-        continue-on-error: true
         with:
           until: "2022-08-20"
+
+      - name: Check output
+        if: "!contains(steps.changed-files-until.outputs.all_changed_files, 'entrypoint.sh')"
+        run: |
+          echo "Invalid output: Expected to include (entrypoint.sh) got (${{ steps.changed-files-until.outputs.all_changed_files }})"
+          exit 1
+        shell:
+          bash
 
       - name: Show output
         run: |
