Updated the test.

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -446,6 +446,27 @@ jobs:
           exit 1
         shell:
           bash
+      - name: Run changed-files with dir_names and dir_names_exclude_root
+        id: changed-files-dir-names-exclude-root
+        uses: ./
+        with:
+          base_sha: dddfbd69
+          sha: 1982157
+          fetch_depth: 60000
+          dir_names: "true"
+          dir_names_exclude_root: "true"
+      - name: Show output
+        run: |
+          echo '${{ toJSON(steps.changed-files-dir-names-exclude-root.outputs) }}'
+        shell:
+          bash
+      - name: Check dir_names output
+        if: steps.changed-files-dir-names-exclude-root.outputs.all_changed_files != ""
+        run: |
+          echo "Invalid output: Expected (empty) got (${{ steps.changed-files-dir-names-exclude-root.outputs.all_changed_files }})"
+          exit 1
+        shell:
+          bash
       - name: Run changed-files with dir_names
         id: changed-files-dir-names
         uses: ./
